In [39]:
from mxnet import nd

In [40]:
x = nd.arange(12)
print(x, x.shape, x.size, x.reshape((3, 4)))
print(nd.zeros((3,4,5)), nd.ones((2,3)), nd.array([[1,2,3],[2,3,4],[3,4,5]]))
print(nd.random.normal(2, 1, shape=(3,4)))


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)> (12,) 12 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
<NDArray 3x4x5 @cpu(0)> 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)> 
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
<NDArray 3x3 @cpu(0)>

[[2.2444217 1.9628394 1.5122501 1.9773828]
 [2.574614  3.4661262 2.6862903 2.354961 ]
 [3.0731697 2.1201746 1.0288898 1.2243034]]
<NDArray 3x4 @cpu(0)>


#### operators: 

In [41]:
X = nd.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
Y = nd.ones((3,4)) 
print(X + Y, X * Y, X / Y)
print(Y.exp())
print(nd.dot(X, Y.T))
print(nd.concat(X, Y), nd.concat(X, Y, dim=0))
print(X == Y, X.sum(), X.norm().asscalar())


[[2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]
<NDArray 3x4 @cpu(0)> 
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
<NDArray 3x4 @cpu(0)> 
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
<NDArray 3x4 @cpu(0)>

[[2.7182817 2.7182817 2.7182817 2.7182817]
 [2.7182817 2.7182817 2.7182817 2.7182817]
 [2.7182817 2.7182817 2.7182817 2.7182817]]
<NDArray 3x4 @cpu(0)>

[[10. 10. 10.]
 [14. 14. 14.]
 [18. 18. 18.]]
<NDArray 3x3 @cpu(0)>

[[1. 2. 3. 4. 1. 1. 1. 1.]
 [2. 3. 4. 5. 1. 1. 1. 1.]
 [3. 4. 5. 6. 1. 1. 1. 1.]]
<NDArray 3x8 @cpu(0)> 
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 6x4 @cpu(0)>

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)> 
[42.]
<NDArray 1 @cpu(0)> 13.038405


### broadcasting and referencing

In [42]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
print(A, B)
print(A + B)


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)> 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>


In [44]:
print(X, X[0:2], X[0, 2])
X[2, :] = 12
print(X)


[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)> 
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]]
<NDArray 2x4 @cpu(0)> 
[3.]
<NDArray 1 @cpu(0)>

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>


### memory referecing

###### allocate new memory 

In [58]:
before = id(Y)
Y = Y + X
print(before, id(Y))

139885685259288 139885685258952
139885685259288 139885685259288


###### allocate new memory and copy it to the old memory space

In [59]:
Y0 = Y.zeros_like()
before = id(Y0)
Y0[:] = Y + X
print(before, id(Y0))

139885685259176 139885685259176


###### directly write to the old space

In [61]:
nd.elemwise_add(X, Y, out=Y0)
print(id(Y0) == before)

True


###### conversion with numpy

In [73]:
import numpy as np

P = np.ones((2, 3))
D = nd.array(P)

print(f'numpy: {P} \n\n NDArray: {D} \n\n back to numpy: {D.asnumpy()}')

numpy: [[1. 1. 1.]
 [1. 1. 1.]] 

 NDArray: 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)> 

 back to numpy: [[1. 1. 1.]
 [1. 1. 1.]]
