In [3]:

from mxnet import autograd, nd

num_inputs = 3 # this time the coeffecients consist of a 2*1 vector + bias
num_examples = 1000
params = nd.array([2, -3.4, 4.2]).reshape(-1, 1)
Xmat = nd.random.normal(scale=1, shape=(num_examples, num_inputs))
labels = nd.dot(Xmat, params)
labels += nd.random.normal(scale=0.01, shape=labels.shape)


[[ 0.40236598  0.34593368 -1.787833  ]
 [-0.17870884  0.9868496  -0.82165414]
 [ 1.1886557  -0.51751894 -0.21166277]
 ...
 [-0.849232    0.2788783  -1.7007854 ]
 [ 0.83491737 -0.368549   -0.7033328 ]
 [-1.3463846   0.7553509   0.34649765]]
<NDArray 1000x3 @cpu(0)>
