In [3]:
import torch
from torch import nn
from torch.nn import init
import numpy as np
import sys
import d2lzh_pytorch as d2l
import time
import ipdb
sys.path.append('..')

In [4]:
num_inputs, num_outputs, num_hiddens = 784, 10, 256

net = nn.Sequential(
    d2l.FlattenLayer(),
    nn.Linear(num_inputs, num_hiddens),
    nn.ReLU(),
    nn.Linear(num_hiddens, num_outputs)
)

for param in net.parameters():
    print(param.shape, param)
    init.normal_(param, mean=0, std=0.01)
    

torch.Size([256, 784]) Parameter containing:
tensor([[-0.0266,  0.0253, -0.0125,  ...,  0.0015,  0.0146,  0.0248],
        [ 0.0142, -0.0036,  0.0058,  ...,  0.0249, -0.0072, -0.0129],
        [ 0.0197, -0.0090, -0.0299,  ...,  0.0334,  0.0340, -0.0047],
        ...,
        [-0.0348, -0.0148,  0.0310,  ...,  0.0089,  0.0098,  0.0019],
        [ 0.0114,  0.0026, -0.0336,  ..., -0.0299,  0.0051, -0.0156],
        [-0.0144, -0.0219,  0.0353,  ...,  0.0044, -0.0292,  0.0161]],
       requires_grad=True)
torch.Size([256]) Parameter containing:
tensor([ 0.0353,  0.0182, -0.0095,  0.0108, -0.0207,  0.0168,  0.0134, -0.0084,
        -0.0003,  0.0059,  0.0253,  0.0231,  0.0266, -0.0074,  0.0267, -0.0140,
        -0.0137,  0.0249, -0.0217,  0.0208, -0.0098, -0.0224, -0.0312, -0.0142,
        -0.0249,  0.0186,  0.0300, -0.0121, -0.0229,  0.0033,  0.0288,  0.0120,
         0.0078, -0.0165,  0.0090, -0.0090,  0.0011, -0.0127, -0.0145, -0.0052,
         0.0084,  0.0352,  0.0259, -0.0279,  0.0269,  

In [5]:
def evaluate_accuracy(data_iter, net):
    acc_sum, n = .0, 0
    with torch.no_grad():
        for X, y in data_iter:
            net.eval()
            acc_sum += (net(X).argmax(dim=1) == y).float().sum().item()
            net.train()
            n += y.shape[0]
        net.eval()
    return acc_sum / n

In [ ]:
# train model
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)
loss = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.5)
num_epochs = 5
n = 0

for e in range(num_epochs):
    train_l_loss, train_acc_sum, n = 0, 0, 0
    for X, y in train_iter:
        y_hat = net(X)
        l = loss(y_hat, y).sum()
        # clear grad 
        optimizer.zero_grad()
        # back-prop
        l.backward()
        optimizer.step()
        train_l_loss += l.item()
        train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
        n += y.shape[0]
        ipdb.set_trace()
    print('epoch %d, loss: %.4f train acc: %.4f test acc: %.4f' % (e + 1, train_l_loss / n, train_acc_sum / n, evaluate_accuracy(test_iter, net)))



> <ipython-input-6-e34b34e1ee01>(11)<module>()
     10     train_l_loss, train_acc_sum, n = 0, 0, 0
---> 11     for X, y in train_iter:
     12         y_hat = net(X)

ipdb> y
tensor([3, 1, 0, 9, 0, 9, 0, 4, 8, 2, 5, 8, 9, 4, 2, 5, 0, 3, 0, 8, 6, 0, 1, 2,
        7, 9, 8, 0, 6, 0, 2, 4, 1, 2, 4, 3, 8, 3, 0, 8, 0, 6, 0, 7, 0, 6, 6, 1,
        9, 2, 4, 3, 3, 1, 4, 9, 8, 8, 7, 9, 3, 0, 1, 0, 9, 3, 4, 8, 3, 2, 2, 2,
        3, 7, 1, 2, 8, 6, 2, 7, 2, 8, 0, 9, 3, 0, 5, 8, 8, 5, 0, 3, 9, 6, 9, 6,
        8, 2, 0, 3, 8, 9, 8, 1, 7, 6, 8, 0, 3, 1, 5, 3, 1, 5, 8, 1, 9, 1, 5, 6,
        1, 9, 7, 5, 0, 6, 0, 2, 1, 6, 5, 0, 2, 1, 0, 4, 1, 8, 0, 0, 3, 9, 5, 9,
        7, 8, 5, 3, 2, 6, 9, 8, 7, 9, 0, 0, 1, 4, 4, 9, 1, 1, 0, 2, 2, 6, 3, 5,
        0, 8, 5, 9, 9, 1, 5, 8, 2, 2, 9, 7, 7, 5, 7, 3, 9, 1, 3, 4, 2, 0, 7, 7,
        5, 4, 5, 0, 2, 5, 0, 7, 7, 9, 1, 8, 3, 9, 0, 9, 4, 7, 0, 4, 5, 6, 4, 2,
        9, 8, 9, 6, 9, 5, 6, 2, 6, 9, 3, 1, 2, 5, 0, 4, 3, 0, 0, 0, 0, 1, 5, 4,
        5, 9, 7, 2, 5, 7